/* Pokémon Void — Pokédex data (placeholder content; swap in real data/sprites).
   window.VDEX = { TYPES, DEX, STAT_LABELS, STAT_MAX, byDex } */
window.VDEX = (function () {
  const STAT_MAX = 200;
  const STAT_LABELS = { HP: 'HP', ATK: 'Attack', DEF: 'Defense', SPA: 'Sp. Atk', SPD: 'Sp. Def', SPE: 'Speed' };

  // 18 standard types + 2 custom (LIGHT, COSMIC), tuned for the dark cosmic theme.
  const TYPES = {
    NORMAL: { name: 'Normal', bg: '#4a463f', glow: '#bdb4a6', fg: '#efeae2' },
    FIRE: { name: 'Fire', bg: '#7a3318', glow: '#ff7a3c', fg: '#ffe6d6' },
    WATER: { name: 'Water', bg: '#1c456e', glow: '#3c9bff', fg: '#d9ecff' },
    ELECTRIC: { name: 'Electric', bg: '#6e5a12', glow: '#ffd23c', fg: '#fff7d6' },
    GRASS: { name: 'Grass', bg: '#27531f', glow: '#5fd13c', fg: '#e0ffd6' },
    ICE: { name: 'Ice', bg: '#1f5a5e', glow: '#5fe6e0', fg: '#dafcff' },
    FIGHTING: { name: 'Fighting', bg: '#6e2420', glow: '#ff5f4c', fg: '#ffe0db' },
    POISON: { name: 'Poison', bg: '#4a1f5e', glow: '#c45fff', fg: '#f3deff' },
    GROUND: { name: 'Ground', bg: '#5e451f', glow: '#e0a85f', fg: '#fff0d6' },
    FLYING: { name: 'Flying', bg: '#2f3f6e', glow: '#8aa8ff', fg: '#e0e8ff' },
    PSYCHIC: { name: 'Psychic', bg: '#7a2f57', glow: '#ff5fa2', fg: '#ffe1ee' },
    BUG: { name: 'Bug', bg: '#4a5e1f', glow: '#b4d13c', fg: '#f1ffd6' },
    ROCK: { name: 'Rock', bg: '#5e5230', glow: '#cbb472', fg: '#fff6dc' },
    GHOST: { name: 'Ghost', bg: '#43356b', glow: '#a07bd6', fg: '#e9defb' },
    DRAGON: { name: 'Dragon', bg: '#2d2470', glow: '#7c6cff', fg: '#e3dcff' },
    DARK: { name: 'Dark', bg: '#2a2329', glow: '#8a7b8e', fg: '#e7e0e8' },
    STEEL: { name: 'Steel', bg: '#3c454d', glow: '#9fb3c2', fg: '#e8edf2' },
    FAIRY: { name: 'Fairy', bg: '#6e2f55', glow: '#ff8ad1', fg: '#ffe3f4' },
    LIGHT: { name: 'Light', bg: '#4a4212', glow: '#ffe566', fg: '#fffce8' },
    COSMIC: { name: 'Cosmic', bg: '#15375e', glow: '#33d6ff', fg: '#dff1ff' },
  };

  // Learnset entries store only lv + name (+ optional sig flag for signature-move styling).
  // Full move data (type, class, power, acc, pp, desc) lives in VGAME.MOVES and is looked up at render time.
  const M = (lv, name, sig) => ({ lv, name, ...(sig ? { sig } : {}) });
  const EGG = (name, sig) => ({ lv: 'EGG', name, ...(sig ? { sig } : {}) });
  const TM = (num, name, sig) => ({ lv: `TM${String(num).padStart(2, '0')}`, name, ...(sig ? { sig } : {}) });

  const DEX = [
    {
      dex: '001', name: 'Tamatoo', category: 'Mudcake', types: ['GRASS'],
      height: '1\'05" ft', weight: '25.3 lbs', catchRate: 140, found: ['Saudade Town (Starter)'],
      abilities: ['Overgrow'],
      hidden: 'Stamina',
      stats: { HP: 54, ATK: 58, DEF: 58, SPA: 40, SPD: 50, SPE: 50 },
      flavor: 'To get nutrition, Tamatoo chews soil in its mouth like gum. After the soil has lost its nutrients, it spits out small pucks of dirt called “Mud Cakes”.',
      evo: { to: '002', method: 'Lv 16' },
      levelMoves: [
        M('1', 'Tackle'),
        M('5', 'Defense Curl'),
        M('7', 'Leafage'),
        M('11', 'Barrage'),
        M('15', 'Grass Whistle'),
        M('18', 'Razor Leaf'),
        M('22', 'Worry Seed'),
        M('25', 'Headbutt'),
        M('29', 'Stealth Rock'),
        M('32', 'Rock Blast'),
        M('36', 'Bulk Up'),
        M('39', 'Stone Edge'),
        M('43', 'Leaf Storm'),
      ],
      eggMoves: [
        EGG('Grassy Glide'),
        EGG('Vital Throw'),
      ],
      tmMoves: [
        TM('01', 'Work Up'),
        TM('02', 'Rest'),
        TM('03', 'Protect'),
      ],
      // anomaly: {discoverer: 'username'},
      anomaly: null,
      evYield: { DEF: 1 }, baseFriendship: 50, baseExp: 64, growthRate: 'Parabolic',
      eggGroups: ['Field', 'Grass'], gender: { m: 87.5, f: 12.5 }, eggCycles: 5120,
    },
    {
      dex: '002', name: 'Terradua', category: 'Stoneroller', types: ['GRASS', 'ROCK'],
      height: '4\'08" ft', weight: '1471 lbs', catchRate: 45, found: [],
      abilities: ['Overgrow'],
      hidden: 'Stamina',
      stats: { HP: 64, ATK: 83, DEF: 83, SPA: 55, SPD: 65, SPE: 65 },
      flavor: 'Terradua treat their boulders with lots of tender love and care. Some have boulders so well kept that they sparkle like crystals.',
      evo: { from: '001', method: 'Lv 16', to: '003', method: 'Lv 38'},
      levelMoves: [
        M('0', 'Rock Tomb'),
        M('1', 'Rock Tomb'),
        M('1', 'Tackle'),
        M('1', 'Defense Curl'),
        M('1', 'Leafage'),
        M('1', 'Barrage'),
        M('15', 'Grass Whistle'),
        M('19', 'Razor Leaf'),
        M('24', 'Worry Seed'),
        M('28', 'Headbutt'),
        M('33', 'Stealth Rock'),
        M('37', 'Rock Blast'),
        M('42', 'Bulk Up'),
        M('46', 'Stone Edge'),
        M('50', 'Leaf Storm'),
      ],
      eggMoves: [],
      tmMoves: [
        TM('01', 'Work Up'),
        TM('02', 'Rest'),
        TM('03', 'Protect'),
        TM('04', 'Bulldoze')
      ],
      // anomaly: {discoverer: 'username'},
      anomaly: null,
      evYield: { DEF: 1, ATK: 1 }, baseFriendship: 50, baseExp: 142, growthRate: 'Parabolic',
      eggGroups: ['Field', 'Grass'], gender: { m: 87.5, f: 12.5 }, eggCycles: 5120,
    },
    {
      dex: '003', name: 'Terratlus', category: 'World Defender', types: ['GRASS', 'ROCK'],
      height: '7\'07" ft', weight: '1568 lbs', catchRate: 45, found: [],
      abilities: ['Gaia Guardian', 'Overgrow'],
      hidden: 'Stamina',
      stats: { HP: 84, ATK: 103, DEF: 118, SPA: 70, SPD: 80, SPE: 75 },
      flavor: 'Terratlus, known as "Protectors", are calm and kind, devoted to the rock they\'ve kept. It\'s said that their rocks hold the light of the world.',
      evo: { from: '002', method: 'Lv 38'},
      forms: [
        {
          name: 'Guardian Form',
          trigger: 'Activates while Grassy Terrain is on the battlefield.',
          types: ['LIGHT', 'GRASS'],
          spriteSuffix: 'F:',
          stats: { HP: 84, ATK: 103, DEF: 70, SPA: 118, SPD: 80, SPE: 75 },
          desc: 'Terratlus draws power from the terrain, causing the moss and crystals across its shell to bloom with protective energy.',
        },
      ],
      levelMoves: [
        M('0', 'Divine Gift'),
        M('1', 'Divine Gift'),
        M('1', 'Rock Tomb'),
        M('1', 'Tackle'),
        M('1', 'Defense Curl'),
        M('1', 'Leafage'),
        M('1', 'Barrage'),
        M('11', 'Seismic Toss'),
        M('15', 'Grass Whistle'),
        M('19', 'Razor Leaf'),
        M('24', 'Worry Seed'),
        M('28', 'Headbutt'),
        M('33', 'Stealth Rock'),
        M('39', 'Rock Blast'),
        M('46', 'Bulk Up'),
        M('52', 'Chi Blast'),
        M('59', 'Stone Edge'),
        M('66', 'Leaf Storm')
      ],
      eggMoves: [],
      tmMoves: [
        TM('01', 'Work Up'),
        TM('02', 'Rest'),
        TM('03', 'Protect'),
        TM('04', 'Bulldoze'),
        TM('05', 'Revealing Light'),
      ],
      // anomaly: {discoverer: 'username'},
      anomaly: null,
      evYield: { DEF: 2, ATK: 1 }, baseFriendship: 50, baseExp: 236, growthRate: 'Parabolic',
      eggGroups: ['Field', 'Grass'], gender: { m: 87.5, f: 12.5 }, eggCycles: 5120,
    },
    {
      dex: '067', name: 'Sedimite', category: 'Potential', types: ['ROCK'],
      height: '4\'08" ft', weight: '1471 lbs', catchRate: 45, found: [],
      abilities: ['Sturdy'],
      hidden: 'Adaptability',
      stats: { HP: 50, ATK: 50, DEF: 50, SPA: 50, SPD: 50, SPE: 40 },
      flavor: 'Sedimite has a cute and friendly nature, sometimes placing random rocks and items into its core purely for fun.',
      evo: { to: ['068','069', '070', '071', '072', '073', '074', '075', '076', '077', '078',]},
      levelMoves: [
      ],
      eggMoves: [],
      tmMoves: [
      ],
      // anomaly: {discoverer: 'username'},
      anomaly: null,
      evYield: { DEF: 1, ATK: 1 }, baseFriendship: 50, baseExp: 142, growthRate: 'Parabolic',
      eggGroups: ['Field', 'Grass'], gender: { m: 87.5, f: 12.5 }, eggCycles: 5120,
    },
    {
      dex: '068', name: 'Sedimage', category: 'Potential', types: ['ROCK'],
      height: '4\'08" ft', weight: '1471 lbs', catchRate: 45, found: [],
      abilities: ['Sturdy'],
      hidden: 'Adaptability',
      stats: { HP: 50, ATK: 50, DEF: 50, SPA: 50, SPD: 50, SPE: 40 },
      flavor: 'Sedimite has a cute and friendly nature, sometimes placing random rocks and items into its core purely for fun.',
      evo: { from: '067', method: 'Fire Stone'},
      levelMoves: [
      ],
      eggMoves: [],
      tmMoves: [
      ],
      // anomaly: {discoverer: 'username'},
      anomaly: null,
      evYield: { DEF: 1, ATK: 1 }, baseFriendship: 50, baseExp: 142, growthRate: 'Parabolic',
      eggGroups: ['Field', 'Grass'], gender: { m: 87.5, f: 12.5 }, eggCycles: 5120,
    },
    {
      dex: '069', name: 'Sedimonk', category: 'Potential', types: ['ROCK'],
      height: '4\'08" ft', weight: '1471 lbs', catchRate: 45, found: [],
      abilities: ['Sturdy'],
      hidden: 'Adaptability',
      stats: { HP: 50, ATK: 50, DEF: 50, SPA: 50, SPD: 50, SPE: 40 },
      flavor: 'Sedimite has a cute and friendly nature, sometimes placing random rocks and items into its core purely for fun.',
      evo: { from: '067', method: 'Water Stone'},
      levelMoves: [
      ],
      eggMoves: [],
      tmMoves: [
      ],
      // anomaly: {discoverer: 'username'},
      anomaly: null,
      evYield: { DEF: 1, ATK: 1 }, baseFriendship: 50, baseExp: 142, growthRate: 'Parabolic',
      eggGroups: ['Field', 'Grass'], gender: { m: 87.5, f: 12.5 }, eggCycles: 5120,
    },
    {
      dex: '070', name: 'Sedruid', category: 'Potential', types: ['ROCK'],
      height: '4\'08" ft', weight: '1471 lbs', catchRate: 45, found: [],
      abilities: ['Sturdy'],
      hidden: 'Adaptability',
      stats: { HP: 50, ATK: 50, DEF: 50, SPA: 50, SPD: 50, SPE: 40 },
      flavor: 'Sedimite has a cute and friendly nature, sometimes placing random rocks and items into its core purely for fun.',
      evo: { from: '067', method: 'Leaf Stone'},
      levelMoves: [
      ],
      eggMoves: [],
      tmMoves: [
      ],
      // anomaly: {discoverer: 'username'},
      anomaly: null,
      evYield: { DEF: 1, ATK: 1 }, baseFriendship: 50, baseExp: 142, growthRate: 'Parabolic',
      eggGroups: ['Field', 'Grass'], gender: { m: 87.5, f: 12.5 }, eggCycles: 5120,
    },
    {
      dex: '071', name: 'Sedificer', category: 'Potential', types: ['ROCK'],
      height: '4\'08" ft', weight: '1471 lbs', catchRate: 45, found: [],
      abilities: ['Sturdy'],
      hidden: 'Adaptability',
      stats: { HP: 50, ATK: 50, DEF: 50, SPA: 50, SPD: 50, SPE: 40 },
      flavor: 'Sedimite has a cute and friendly nature, sometimes placing random rocks and items into its core purely for fun.',
      evo: { from: '067', method: 'Thunder Stone'},
      levelMoves: [
      ],
      eggMoves: [],
      tmMoves: [
      ],
      // anomaly: {discoverer: 'username'},
      anomaly: null,
      evYield: { DEF: 1, ATK: 1 }, baseFriendship: 50, baseExp: 142, growthRate: 'Parabolic',
      eggGroups: ['Field', 'Grass'], gender: { m: 87.5, f: 12.5 }, eggCycles: 5120,
    },
    {
      dex: '072', name: 'Sedimage', category: 'Potential', types: ['ROCK'],
      height: '4\'08" ft', weight: '1471 lbs', catchRate: 45, found: [],
      abilities: ['Sturdy'],
      hidden: 'Adaptability',
      stats: { HP: 50, ATK: 50, DEF: 50, SPA: 50, SPD: 50, SPE: 40 },
      flavor: 'Sedimite has a cute and friendly nature, sometimes placing random rocks and items into its core purely for fun.',
      evo: { from: '067', method: 'Sun Stone'},
      levelMoves: [
      ],
      eggMoves: [],
      tmMoves: [
      ],
      // anomaly: {discoverer: 'username'},
      anomaly: null,
      evYield: { DEF: 1, ATK: 1 }, baseFriendship: 50, baseExp: 142, growthRate: 'Parabolic',
      eggGroups: ['Field', 'Grass'], gender: { m: 87.5, f: 12.5 }, eggCycles: 5120,
    },
    {
      dex: '073', name: 'Sedirogue', category: 'Potential', types: ['ROCK'],
      height: '4\'08" ft', weight: '1471 lbs', catchRate: 45, found: [],
      abilities: ['Sturdy'],
      hidden: 'Adaptability',
      stats: { HP: 50, ATK: 50, DEF: 50, SPA: 50, SPD: 50, SPE: 40 },
      flavor: 'Sedimite has a cute and friendly nature, sometimes placing random rocks and items into its core purely for fun.',
      evo: { from: '067', method: 'Moon Stone'},
      levelMoves: [
      ],
      eggMoves: [],
      tmMoves: [
      ],
      // anomaly: {discoverer: 'username'},
      anomaly: null,
      evYield: { DEF: 1, ATK: 1 }, baseFriendship: 50, baseExp: 142, growthRate: 'Parabolic',
      eggGroups: ['Field', 'Grass'], gender: { m: 87.5, f: 12.5 }, eggCycles: 5120,
    },
    {
      dex: '074', name: 'Sediserker', category: 'Potential', types: ['ROCK'],
      height: '4\'08" ft', weight: '1471 lbs', catchRate: 45, found: [],
      abilities: ['Sturdy'],
      hidden: 'Adaptability',
      stats: { HP: 50, ATK: 50, DEF: 50, SPA: 50, SPD: 50, SPE: 40 },
      flavor: 'Sedimite has a cute and friendly nature, sometimes placing random rocks and items into its core purely for fun.',
      evo: { from: '067', method: 'Ice Stone'},
      levelMoves: [
      ],
      eggMoves: [],
      tmMoves: [
      ],
      // anomaly: {discoverer: 'username'},
      anomaly: null,
      evYield: { DEF: 1, ATK: 1 }, baseFriendship: 50, baseExp: 142, growthRate: 'Parabolic',
      eggGroups: ['Field', 'Grass'], gender: { m: 87.5, f: 12.5 }, eggCycles: 5120,
    },
    {
      dex: '075', name: 'Sediranger', category: 'Potential', types: ['ROCK'],
      height: '4\'08" ft', weight: '1471 lbs', catchRate: 45, found: [],
      abilities: ['Sturdy'],
      hidden: 'Adaptability',
      stats: { HP: 50, ATK: 50, DEF: 50, SPA: 50, SPD: 50, SPE: 40 },
      flavor: 'Sedimite has a cute and friendly nature, sometimes placing random rocks and items into its core purely for fun.',
      evo: { from: '067', method: 'Dawn Stone'},
      levelMoves: [
      ],
      eggMoves: [],
      tmMoves: [
      ],
      // anomaly: {discoverer: 'username'},
      anomaly: null,
      evYield: { DEF: 1, ATK: 1 }, baseFriendship: 50, baseExp: 142, growthRate: 'Parabolic',
      eggGroups: ['Field', 'Grass'], gender: { m: 87.5, f: 12.5 }, eggCycles: 5120,
    },
    {
      dex: '076', name: 'Sedimancer', category: 'Potential', types: ['ROCK'],
      height: '4\'08" ft', weight: '1471 lbs', catchRate: 45, found: [],
      abilities: ['Sturdy'],
      hidden: 'Adaptability',
      stats: { HP: 50, ATK: 50, DEF: 50, SPA: 50, SPD: 50, SPE: 40 },
      flavor: 'Sedimite has a cute and friendly nature, sometimes placing random rocks and items into its core purely for fun.',
      evo: { from: '067', method: 'Dusk Stone'},
      levelMoves: [
      ],
      eggMoves: [],
      tmMoves: [
      ],
      // anomaly: {discoverer: 'username'},
      anomaly: null,
      evYield: { DEF: 1, ATK: 1 }, baseFriendship: 50, baseExp: 142, growthRate: 'Parabolic',
      eggGroups: ['Field', 'Grass'], gender: { m: 87.5, f: 12.5 }, eggCycles: 5120,
    },
    {
      dex: '077', name: 'Sediric', category: 'Potential', types: ['ROCK'],
      height: '4\'08" ft', weight: '1471 lbs', catchRate: 45, found: [],
      abilities: ['Sturdy'],
      hidden: 'Adaptability',
      stats: { HP: 50, ATK: 50, DEF: 50, SPA: 50, SPD: 50, SPE: 40 },
      flavor: 'Sedimite has a cute and friendly nature, sometimes placing random rocks and items into its core purely for fun.',
      evo: { from: '067', method: 'Shiny Stone'},
      levelMoves: [
      ],
      eggMoves: [],
      tmMoves: [
      ],
      // anomaly: {discoverer: 'username'},
      anomaly: null,
      evYield: { DEF: 1, ATK: 1 }, baseFriendship: 50, baseExp: 142, growthRate: 'Parabolic',
      eggGroups: ['Field', 'Grass'], gender: { m: 87.5, f: 12.5 }, eggCycles: 5120,
    },
    {
      dex: '078', name: 'Sedilock', category: 'Potential', types: ['ROCK'],
      height: '4\'08" ft', weight: '1471 lbs', catchRate: 45, found: [],
      abilities: ['Sturdy'],
      hidden: 'Adaptability',
      stats: { HP: 50, ATK: 50, DEF: 50, SPA: 50, SPD: 50, SPE: 40 },
      flavor: 'Sedimite has a cute and friendly nature, sometimes placing random rocks and items into its core purely for fun.',
      evo: { from: '067', method: 'Cosmic Stone'},
      levelMoves: [
      ],
      eggMoves: [],
      tmMoves: [
      ],
      // anomaly: {discoverer: 'username'},
      anomaly: null,
      evYield: { DEF: 1, ATK: 1 }, baseFriendship: 50, baseExp: 142, growthRate: 'Parabolic',
      eggGroups: ['Field', 'Grass'], gender: { m: 87.5, f: 12.5 }, eggCycles: 5120,
    },
  ];

  const byDex = (n) => DEX.find((d) => d.dex === String(n));

  return { TYPES, DEX, STAT_LABELS, STAT_MAX, byDex };
})();
